### PR TITLE
Filter enhancement

### PR DESCRIPTION
**Pull request by Stanko2**
Ability to filter documents by open status, tags, scoring

Test if everything is working. If you have any other commands to add just write it here :smiley_cat:

### CODE REVIEW

**Comment by jaksia** [comment]
I like the way filters work, in future a gui configurator can be added (quite low priority for now).  

Had a low of trouble with tags during testing. When switching solutions the tag menu glitches. You can add and remove tags but it doesn't visually update. Tag filtering sometime works but mostly not. I couldn't find any specific pattern, seems to be random. No console errors, nor warnings.
Might be beneficial to rebase onto latest `dev`, so that fix for tags will not cause issues with ef428794 after merge.

I suggest adding a filter for solutions with a comment.

**Review by jaksia — CHANGES_REQUESTED** [review]
I like the way filters work, in future a gui configurator can be added (quite low priority for now).  

Had a low of trouble with tags during testing. When switching solutions the tag menu glitches. You can add and remove tags but it doesn't visually update. Tag filtering sometime works but mostly not. I couldn't find any specific pattern, seems to be random. No console errors, nor warnings.
Might be beneficial to rebase onto latest `dev`, so that fix for tags will not cause issues with ef428794 after merge.

I suggest adding a filter for solutions with a comment.

**Comment by Stanko2** [comment]
Added filter for solutions that contain comment, fixed tag filter

**Review by jaksia — APPROVED** [review]
Everything tested works, looks good to go

**Pull request merged**
