### PR TITLE
Custom colors, adding page doesn't remove annotations

### PR DESCRIPTION
**Pull request by jaksia**
Allows choosing custom color in color picker.
Implemented #39, from my testing it works great. Please test it a bit more.

### CODE REVIEW

**Comment by Stanko2** [comment]
On Image PDFs doesn't add a new page, on others working fine (Don't know if it was happening previously or it appeared now for the first time). Colorpicker working fine, but consider removing the ugly white border around the button.

**Review by Stanko2 — COMMENTED** [review]
On Image PDFs doesn't add a new page, on others working fine (Don't know if it was happening previously or it appeared now for the first time). Colorpicker working fine, but consider removing the ugly white border around the button.

**Comment by Stanko2** [comment]
To be more specific on this one it wasn't working:
[p8-c8-adam-brdecka-11988.pdf](https://github.com/Stanko2/arnold/files/9904959/p8-c8-adam-brdecka-11988.pdf)

**Comment by jaksia** [comment]
Somewhat fixed, now uses `AddTrailingPage` instead of `GeneratePDF` when no image rotation was detected.

From my testing, some solutions with images did not experience this at all (even tho they probably should have). I have no idea why that is, might be a good idea to look into this in future.

**Review by Stanko2 — APPROVED** [review]
All fine, merging

**Pull request merged**
